<form>
    <!-- <div class="form-group">
        <label for="inputName">Nome</label>
        <input type="text" class="form-control" id="inputUser" placeholder="Usuário">
    </div> -->
    <div class="form-group">
        <label for="inputEmail">E-mail</label>
        <input type="email" class="form-control" id="inputEmailLogin" placeholder="E-mail">
    </div>
    <div class="form-group">
        <label for="inputPassword">Senha</label>
        <input type="password" class="form-control" id="inputPasswordLogin" placeholder="Password">
    </div>
</form>
<button class="btn btn-primary" id="login">Entrar</button>

<p class="redirect"><a href='<?= HOME_URL?>/User/formSignInAction'>Ainda não tem uma conta? Crie uma clicando aqui!</a></p>
<p class="redirect"><a href='<?= HOME_URL?>/User/formForgotPassword'>Esqueceu da sua senha? Gere uma nova aqui!</a></p>
<script src="<?= HOME_URL ?>/scripts/login.js"></script>
<script src="<?= HOME_URL ?>/scripts/userManager.js"></script>